title: <p align="center">  Venkata Sreenivasulu </p>
logo: /assets/img/logo.png
description:
<p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/srinu11704926918277/">LinkedIn</a> |
  <a href="https://github.com/Srinuvas456">GitHub</a>
  
  <br>  
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
